######################## default configuration ####################
baseURL = "https://fanfever.github.io/hongsheng-tich/"
title = "鸿升科技 - 专业的广告设计与技术开发服务"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true