############################# Chinese ############################
[zh]
languageName = "中文"
languageCode = "zh-CN"
contentDir = "content/chinese"
weight = 1
title = "鸿升科技"

[zh.params]
footer_menu_left = "公司"
footer_menu_middle = "产品"
footer_menu_right = "支持"
footer_content = "鸿升科技致力于为企业提供专业的设计与技术服务"
copyright = "版权所有 © 2024 鸿升科技"



############################# English ############################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 2
title = "HongSheng Tech"

[en.params]
footer_menu_left = "Company"
footer_menu_middle = "Products"
footer_menu_right = "Support"
footer_content = "HongSheng Tech is committed to providing professional design and technical services for enterprises"
copyright = "Copyright © 2024 HongSheng Tech"
