# main menu
[[main]]
name = "Startseite"
url = ""
weight = 1

[[main]]
name = "Nachrichten"
url = "blog/"
weight = 2

[[main]]
name = "Preise"
url = "pricing/"
weight = 3

[[main]]
name = "Kontakt"
url = "contact/"
weight = 4

[[main]]
name = "FAQ"
url = "faq/"
weight = 5

# footer menu left
[[footer_left]]
name = "Über uns"
url = "#"

[[footer_left]]
name = "Schnellstart"
url = "#"

[[footer_left]]
name = "Dienstleistungen"
url = "pricing/"


# footer menu middle
[[footer_middle]]
name = "Dienstleistungen"
url = "pricing/"

[[footer_middle]]
name = "Design-Services"
url = "#"

[[footer_middle]]
name = "Technische Entwicklung"
url = "#"

# footer menu right
[[footer_right]]
name = "Datenschutzerklärung"
url = "privacy-policy/"

[[footer_right]]
name = "Nutzungsbedingungen"
url = "terms-conditions/"

[[footer_right]]
name = "FAQ"
url = "faq/"