# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Service"
url = "service/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "FAQ"
url = "faq/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6

# footer menu
[[footer_left]]
name = "About Us"
url = "#"

[[footer_middle]]
name = "Services"
url = "pricing/"

[[footer_right]]
name = "Support"
url = "contact/"